### ISSUE TITLE
Provider crashes when creating confluent_schema resource

### ISSUE THREAD

**Issue by superkartoffel** [confluentinc/terraform-provider-confluent#258] opened 2023-05-16 08:43 UTC
I use the following setup

schema.tf
```
resource "confluent_schema" "schema" {
  subject_name = "TestNamespace.TestSchema"
  schema = file("testschema.avsc")
  format = "AVRO"

  recreate_on_update = false
  hard_delete = false

  lifecycle {
    prevent_destroy = true
  }
}
```

setup.tf
```
terraform {
  required_version = "1.4.4"

  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.42.0"
    }
  }
}

variable "schema_registry_api_key" {
  description = "Confluent Schema Registry API Key"
  type        = string
}

variable "schema_registry_api_secret" {
  description = "Confluent Schema Registry API Secret"
  type        = string
  sensitive   = true
}

variable "schema_registry_id" {
  description = "Confluent Cloud Schema Registry id"
  type        = string
}

variable "schema_registry_rest_endpoint" {
  description = "Confluent Cloud Schema Registry REST endpoint"
  type        = string
}

provider "confluent" {
  schema_registry_id            = var.schema_registry_id            # optionally use SCHEMA_REGISTRY_ID env var
  schema_registry_rest_endpoint = var.schema_registry_rest_endpoint # optionally use SCHEMA_REGISTRY_REST_ENDPOINT env var
  schema_registry_api_key       = var.schema_registry_api_key       # optionally use SCHEMA_REGISTRY_API_KEY env var
  schema_registry_api_secret    = var.schema_registry_api_secret    # optionally use SCHEMA_REGISTRY_API_SECRET env var
}
```

testschema.avsc
```
{
  "type": "record",
  "name": "TestSchema",
  "namespace": "TestNamespace",
  "fields": [
    {
      "name": "Id",
      "type": "string"
    },
    {
      "name": "Value",
      "type": "string"
    }
  ]
}
```

I set TF_VAR_... variables accordingly to set credentials to the schema registry cluster.
when I run:
```
terraform init
terraform validate
terraform plan -out=tfplan
terraform apply tfplan
```

on the apply step the provider crashes with this message:
```
confluent_schema.schema: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with confluent_schema.schema,
│   on schema.tf line 2, in resource "confluent_schema" "schema":
│    2: resource "confluent_schema" "schema" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-confluent_1.42.0 plugin:

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x236c0 pc=0x236c0]

runtime stack:
runtime.throw({0x13fd3a9?, 0x0?})
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/panic.go:1047 +0x5d fp=0x7efc37fe7d58 sp=0x7efc37fe7d28 pc=0x43809d
runtime.sigpanic()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7efc37fe7db8 sp=0x7efc37fe7d58 pc=0x44e5a9

goroutine 39 [syscall]:
runtime.cgocall(0xf36c80, 0xc0005ba558)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/cgocall.go:157 +0x5c fp=0xc0005ba530 sp=0xc0005ba4f8 pc=0x406fdc
net._C2func_getaddrinfo(0xc0005a01b0, 0x0, 0xc0005e2bd0, 0xc0005c8438)
        /tmp/go-build3196846011/b099/_cgo_gotypes.go:99 +0x56 fp=0xc0005ba558 sp=0xc0005ba530 pc=0x628ed6
net._C_getaddrinfo.func1(0x410ac7?, 0x8?, 0x1201660?, 0xc0005a0101?)
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix_cgo.go:74 +0x85 fp=0xc0005ba5c0 sp=0xc0005ba558 pc=0x629aa5
net._C_getaddrinfo(0x0?, 0x0?, 0x0?, 0xc0005a00c0?)
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix_cgo.go:74 +0x19 fp=0xc0005ba5f0 sp=0xc0005ba5c0 pc=0x6299d9
net.cgoLookupIPCNAME({0x13d0dc7, 0x3}, {0xc0005a00c0, 0x2b})
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:153 +0x175 fp=0xc0005ba738 sp=0xc0005ba5f0 pc=0x5f65b5
net.cgoIPLookup(0x1d7faf0?, {0x13d0dc7?, 0xc0005a00f0?}, {0xc0005a00c0?, 0xc0005c62c0?})
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:210 +0x3b fp=0xc0005ba7a8 sp=0xc0005ba738 pc=0x5f6c7b
net.cgoLookupIP.func1()
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:220 +0x36 fp=0xc0005ba7e0 sp=0xc0005ba7a8 pc=0x5f70b6
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005ba7e8 sp=0xc0005ba7e0 pc=0x46a961
created by net.cgoLookupIP
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:220 +0x12a

goroutine 1 [select]:
runtime.gopark(0xc0004df930?, 0x2?, 0xca?, 0x31?, 0xc0004df7b4?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc0004ef540 sp=0xc0004ef520 pc=0x43ae76
runtime.selectgo(0xc0004ef930, 0xc0004df7b0, 0x1?, 0x0, 0xc0004df970?, 0x1)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/select.go:327 +0x7be fp=0xc0004ef680 sp=0xc0004ef540 pc=0x44a71e
github.com/hashicorp/go-plugin.Serve(0xc0000aa120)
        pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/server.go:469 +0x14a5 fp=0xc0004efb60 sp=0xc0004ef680 pc=0xd3aac5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0x13d5aa8, 0x8}, 0xc000037540, {0x0, 0x0, 0x0})
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:311 +0xc0a fp=0xc0004efda0 sp=0xc0004efb60 pc=0xd52b2a
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf5serverServe(0xc0000aa0c0)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/plugin/serve.go:178 +0x4d9 fp=0xc0004efe80 sp=0xc0004efda0 pc=0xd73e39
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc0000aa0c0)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/plugin/serve.go:118 +0x18d fp=0xc0004eff48 sp=0xc0004efe80 pc=0xd737ed
main.main()
        src/github.com/confluentinc/terraform-provider-confluent/main.go:30 +0x6b fp=0xc0004eff80 sp=0xc0004eff48 pc=0xf36b6b
runtime.main()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:250 +0x207 fp=0xc0004effe0 sp=0xc0004eff80 pc=0x43aa47
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004effe8 sp=0xc0004effe0 pc=0x46a961

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000084fb0 sp=0xc000084f90 pc=0x43ae76
runtime.goparkunlock(...)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:387
runtime.forcegchelper()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:305 +0xb0 fp=0xc000084fe0 sp=0xc000084fb0 pc=0x43acb0
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x46a961
created by runtime.init.6
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000085780 sp=0xc000085760 pc=0x43ae76
runtime.goparkunlock(...)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000857c8 sp=0xc000085780 pc=0x42705e
runtime.gcenable.func1()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:178 +0x26 fp=0xc0000857e0 sp=0xc0000857c8 pc=0x41c2e6
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000857e8 sp=0xc0000857e0 pc=0x46a961
created by runtime.gcenable
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00003c0e0?, 0x1577070?, 0x0?, 0x0?, 0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000085f70 sp=0xc000085f50 pc=0x43ae76
runtime.goparkunlock(...)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1d80700)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000085fa0 sp=0xc000085f70 pc=0x424f53
runtime.bgscavenge(0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000085fc8 sp=0xc000085fa0 pc=0x425545
runtime.gcenable.func2()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:179 +0x26 fp=0xc000085fe0 sp=0xc000085fc8 pc=0x41c286
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000085fe8 sp=0xc000085fe0 pc=0x46a961
created by runtime.gcenable
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x143f9f8?, 0x0?, 0xa0?, 0x1000000010?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000084628 sp=0xc000084608 pc=0x43ae76
runtime.runfinq()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mfinal.go:193 +0x107 fp=0xc0000847e0 sp=0xc000084628 pc=0x41b2a7
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000847e8 sp=0xc0000847e0 pc=0x46a961
created by runtime.createfing
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mfinal.go:163 +0x45


Error: The terraform-provider-confluent_1.42.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Let me know if I can provide any additional information.

**Comment by superkartoffel** [comment] 2023-05-17 09:34
I have created a trace log in case it is helpful: https://gist.github.com/superkartoffel/29217c7956ea9359fcd420793f928aaa

I also tried the POST request that is mentioned in line 1976:
```
$ curl -X POST https://psrc-0j199.westeurope.azure.confluent.cloud/compatibility/subjects/TestNamespace.TestSchema/versions?verbose=true -d '{"references":[],"schema":"{\n  \"type\": \"record\",\n  \"name\": \"TestSchema\",\n  \"namespace\": \"TestNamespace\",\n  \"fields\": [\n    {\n      \"name\": \"Id\",\n      \"type\": \"string\"\n    },\n    {\n      \"name\": \"Value\",\n      \"type\": \"string\"\n    }\n  ]\n}","schemaType":"AVRO"}' --user 'key:secret' -H "Content-Type: application/vnd.schemaregistry.v1+json"
{"is_compatible":true,"messages":[]}
```

**Comment by andredelgado-ruiz** [comment] 2023-05-19 21:50
Hello @superkartoffel , I had the same problem, changing the provider version to 1.39.0 worked, maybe you can try it

**Comment by superkartoffel** [comment] 2023-05-24 08:51
You're right, this seems to be a regression. 1.39.0 works fine.

**Comment by linouk23** [comment] 2023-06-01 06:22
@superkartoffel @andredelgado-ruiz thanks for reporting it!

Could you confirm you're using linux binaries of TF Provider?

Most likely the reason is [this commit](https://github.com/confluentinc/terraform-provider-confluent/commit/043c37def5728e91d6349b467bc5f4c96ef3c21a) but it's not clear to me why it fails still since linux binaries were statically compiled 🤔 (there was a similar [issue](https://github.com/confluentinc/terraform-provider-confluent/issues/205) a while ago where the root cause was TF binaries were dynamically compiled).

**Comment by linouk23** [comment] 2023-06-02 13:32
@superkartoffel @andredelgado-ruiz could you run `terraform version` and share the output of this command?

https://github.com/confluentinc/terraform-provider-confluent/issues/268 indicates it happens for `linux_amd64` at least so I'm wondering whether there's a typo [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/.goreleaser.yml#L39-L58).

**Comment by superkartoffel** [comment] 2023-06-02 14:18
@linouk23 that seems to be the issue. The terraform version out is:
```
Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.42.0

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

I tried latest terraform versions (1.4.6) for linux amd64 and linux 386: amd64 crashes, 386 works as expected.

**Comment by linouk23** [comment] 2023-06-02 21:11
@andredelgado-ruiz are you sure about `darwin_arm64`? That sounds surprising to me since we didn't change any flags for non-linux binaries 😮

**Comment by linouk23** [comment] 2023-06-07 02:16
update: I didn't manage to reproduce an issue when using a config from #268 -- the provider didn't crash:
```
➜  demo19 git:(master) ✗ ls
main.tf      variables.tf
➜  demo19 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest init

Initializing the backend...

Initializing provider plugins...
- Finding confluentinc/confluent versions matching "1.42.0"...
- Installing confluentinc/confluent v1.42.0...
- Installed confluentinc/confluent v1.42.0 (signed by a HashiCorp partner, key ID D4A2B1EDB0EC0C8E)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
➜  demo19 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest plan
var.confluent_cloud_api_key
  Confluent Cloud API Key (also referred as Cloud API ID)

  Enter a value: 

var.confluent_cloud_api_secret
  Confluent Cloud API Secret

  Enter a value: 

data.confluent_environment.main: Reading...
data.confluent_environment.main: Read complete after 0s [id=env-7n1r31]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
➜  demo19 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest version
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.42.0
```

```
# main.tf

terraform {
  required_providers {
    confluent = {
      source = "confluentinc/confluent"
      version = "1.42.0"
    }
  }
}

provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key
  cloud_api_secret = var.confluent_cloud_api_secret
}

data "confluent_environment" "main" {
  id = "env-7n1r31"
}
```

@superkartoffel @cuhsat @andredelgado-ruiz @rickard-von-essen is there a TF config that consistently triggers TF Provider to panic? Can you reproduce it with `hashicorp/terraform:latest` image (linux_amd64) too by running:
```
$ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest init
$ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest plan
```

**Comment by linouk23** [comment] 2023-06-07 02:40
upd: I have also recreated an example referenced in this issue -- the only change was to use a different TF version (1.4.6 instead of 1.4.4):
```
➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest init

Initializing the backend...
╷
│ Error: Unsupported Terraform Core version
│ 
│   on setup.tf line 2, in terraform:
│    2:   required_version = "1.4.4"
│ 
│ This configuration does not support Terraform version 1.4.6. To proceed, either choose another supported Terraform version or update this version constraint. Version
│ constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵
# removed required_version = "1.4.4" from schema.tf here

➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest init

Initializing the backend...

Initializing provider plugins...
- Finding confluentinc/confluent versions matching "1.42.0"...
- Installing confluentinc/confluent v1.42.0...
- Installed confluentinc/confluent v1.42.0 (signed by a HashiCorp partner, key ID D4A2B1EDB0EC0C8E)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest validate
Success! The configuration is valid.

➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest plan -out=tfplan
var.schema_registry_api_key
  Confluent Schema Registry API Key

  Enter a value: DCMGNHUGDYKF....

var.schema_registry_api_secret
  Confluent Schema Registry API Secret

  Enter a value: 

var.schema_registry_id
  Confluent Cloud Schema Registry id

  Enter a value: lsrc-8wrx70

var.schema_registry_rest_endpoint
  Confluent Cloud Schema Registry REST endpoint

  Enter a value: https://psrc-....us-west-2.aws.confluent.cloud


Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # confluent_schema.schema will be created
  + resource "confluent_schema" "schema" {
      + format             = "AVRO"
      + hard_delete        = false
      + id                 = (known after apply)
      + recreate_on_update = false
      + schema             = jsonencode(
            {
              + fields    = [
                  + {
                      + name = "Id"
                      + type = "string"
                    },
                  + {
                      + name = "Value"
                      + type = "string"
                    },
                ]
              + name      = "TestSchema"
              + namespace = "TestNamespace"
              + type      = "record"
            }
        )
      + schema_identifier  = (known after apply)
      + subject_name       = "TestNamespace.TestSchema"
      + version            = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest apply tfplan                
confluent_schema.schema: Creating...
confluent_schema.schema: Still creating... [10s elapsed]
confluent_schema.schema: Creation complete after 10s [id=lsrc-8wrx70/TestNamespace.TestSchema/latest]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest versio  
Terraform has no command named "versio". Did you mean "version"?

To see all of Terraform's top-level commands, run:
  terraform -help

➜  demo192 git:(master) ✗ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest version
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.42.0

```

**Comment by linouk23** [comment] 2023-06-12 19:39
@superkartoffel @cuhsat @andredelgado-ruiz @rickard-von-essen is there a TF config that consistently triggers TF Provider to panic? Can you reproduce it with `hashicorp/terraform:latest` image (linux_amd64) too by running:

```
$ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest init
$ docker run -it -v $(pwd):/tf -w /tf hashicorp/terraform:latest plan
```

Thank you!

**Comment by superkartoffel** [comment] 2023-06-15 07:46
@linouk23 The config in the original report consistently triggers the TF provider to panic when using terraform linux amd64 versions (several tested, including latest 1.5.0). That is using the terraform executables downloaded from https://www.terraform.io/downloads.html running on my machine.

However, using terraform docker image, as you suggested, I cannot reproduce the issue although it is linux_amd64, too.

So, it is probably related to my installation of linux? both the terraform and the providers executables are statically linked, right?

```
$ ldd terraform 
        not a dynamic executable
$ ldd .terraform/providers/registry.terraform.io/confluentinc/confluent/1.43.0/linux_amd64/terraf
orm-provider-confluent_1.43.0 
        not a dynamic executable
$ terraform -version
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.43.0
$ docker run -it hashicorp/terraform:latest -version
Terraform v1.5.0
on linux_amd64
$ uname -a
Linux hvorwerk-linux 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux
$ cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

**Comment by superkartoffel** [comment] 2023-06-16 07:02
I did some further investigation and found that it is most likely a bug in glibc as described here: https://github.com/golang/go/issues/30310

The trace I posted earlier fits and as described in the issue, I can set `GODEBUG=netdns=go` environment variable to work around the issue.

I suggest you try to set `-tags netgo` or document one of the workarounds.

**Comment by linouk23** [comment] 2023-06-16 16:03
Thank you so much for the investigation @superkartoffel! That looks like a super easy fix, we just merged it to our internal repo so it'll be included in our next release 👍

**Comment by linouk23** [comment] 2023-06-20 17:58
@superkartoffel thank you again for your investigation! FYI we have just [released](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md) a new version of TF Provider that should resolve this issue where we [included](https://github.com/confluentinc/terraform-provider-confluent/blob/master/.goreleaser.yml) `-tags=netgo` flag.

I'm resolving this issue but feel free to reopen if you manage to reproduce the issue.

**Closed by linouk23** 2023-06-20 17:58 UTC
Labels: bug, work-in-progress
