### ISSUE TITLE
Schema Evolution - Error (confluent_schema resource)

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#175] opened 2023-01-23 20:27 UTC
I am using the documenation reference from [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/docs/resources/confluent_schema.md#argument-reference) to register a schema (which works) and then evolve it (which fails). 

As I try to evolve the schema, I get the below error
```
 Resource module.[redacted]-value.confluent_schema.topic-schema has
│ lifecycle.prevent_destroy set, but the plan calls for this resource to be
│ destroyed. To avoid this error and continue with the plan, either disable
│ lifecycle.prevent_destroy or reduce the scope of the plan using the -target
│ flag.
```

My definition is as follows
```
resource "confluent_schema" "topic-schema" {
  schema_registry_cluster {
    id = data.confluent_schema_registry_cluster.public.id
  }

  rest_endpoint = data.confluent_schema_registry_cluster.public.rest_endpoint
  subject_name  = var.subject_name
  format        = var.schema_format
  schema        = file(var.schema_file_name)

  credentials {
    key    = var.schema_registry_credentails["schema_registry_key"]
    secret = var.schema_registry_credentails["schema_registry_secret"]
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

For both the runs, I am passing different file that contains the respective schema as it evolves
```
# for initial schema (v1 version that got registered)
/schemas/proto/mytopic-value.proto

# for v2 version (that failed)
/schemas/proto/mytopic-value_v2.proto
```

What am I missing?  Thanks.

**Comment by linouk23** [comment] 2023-01-23 20:31
@bluedog13 that seems like a duplicate of #124 -- it'd be great if you could copy your message there -- there's a huge discussion about it

I'm closing as a duplicate.

**Closed by linouk23** 2023-01-23 20:31 UTC
