### ISSUE TITLE
question: is it possible to use this against a local cluster?

### ISSUE THREAD

**Issue by pwmcintyre** [confluentinc/terraform-provider-confluent#201] opened 2023-02-16 04:36 UTC
i'm looking to experiment with this provider, but i can't seem to run it against a local cluster

eg. you can spin up a local cluster via docker compose:
https://docs.confluent.io/platform/current/platform-quickstart.html#ce-docker-quickstart

how would i configure this provider to deploy a topic to this local cluster?

**Comment by linouk23** [comment] 2023-02-16 06:01
@pwmcintyre thanks for creating the issue! The short answer is it's not possible at the moment. It seems to be a duplicate of https://github.com/confluentinc/terraform-provider-confluent/issues/145 which you might want to subscribe to.

**Closed by linouk23** 2023-02-16 06:01 UTC
