### ISSUE TITLE
Improve error output for confluent_identity_provider

### ISSUE THREAD

**Issue by S1M0NM** [confluentinc/terraform-provider-confluent#208] opened 2023-02-21 20:26 UTC
I was experimenting a bit today with the Identity Providers and OAuth 2.0 for Confluent Cloud and wanted to create a provider connection via Terraform.
However, I always got an error without exact error details. 

```
Error: error creating Identity Provider: 409 Conflict

```

Only when I wanted to create the provider via the Cloud UI with the same data, I got as a detail that a provider with the data already exists.

Would it be possible to display the error details in Terraform?

**Comment by linouk23** [comment] 2023-02-21 22:28
@S1M0NM thanks for reporting the issue!

It's kinda a duplicate of https://github.com/confluentinc/terraform-provider-confluent/issues/21 and the corresponding backend team has this ticket in their backlog.

**Closed** 2023-04-11 21:37 UTC
Labels: invalid
