### ISSUE TITLE
issue creating service account in QA env

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#185] opened 2023-01-30 15:17 UTC
We already creating service account in DEV env.When same service account creating in QA,getting error
error creating Service Account "********-test": 409 Conflict: Service name is already in use

**Comment by linouk23** [comment] 2023-01-30 21:00
Thanks for creating an issue @Davinder2609!

It looks like a duplicate of #92, #48, #28.

Let me know if it helps!

**Closed by linouk23** 2023-01-30 21:00 UTC
Labels: question

**Comment by Davinder2609** [comment] 2023-01-30 21:09
@linouk23  Its in DEV env,Now I am creating in QA env.Deletion is not option for me.

**Comment by linouk23** [comment] 2023-01-30 21:11
@Davinder2609 did you try to [import](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_service_account#import) a service account since it exists already?

**Comment by Davinder2609** [comment] 2023-01-31 15:46
@linouk23 I used i terminal,Do you have any example ,how this information specify in main file

**Comment by linouk23** [comment] 2023-01-31 16:50
Sounds good! Could you confirm you managed to import a service account successfully?

**Comment by linouk23** [comment] 2023-01-31 16:51
cc @Davinder2609

**Comment by Davinder2609** [comment] 2023-01-31 18:05
@linouk23  yes import successfully-
api_version  = "iam/v2"
    description  = "Service account to consume from 'orders' topic of 'inventory' Kafka cluster"
    display_name = "app-consumer"
    id           = "sa-***"
    kind         = "ServiceAccount"

**Comment by Davinder2609** [comment] 2023-01-31 18:41
@linouk23 how to apply this configuration in main file,to check if service account already exist,It should not created

**Comment by linouk23** [comment] 2023-01-31 18:42
I think that's pretty much what you did -- try to create and if there's 409 error -- import it manually.
