### ISSUE TITLE
expose the Azure cloud zones details when a private link Dedicated SingleZone Cluster has been deployed 

### ISSUE THREAD

**Issue by huangfulibo** [confluentinc/terraform-provider-confluent#213] opened 2023-03-01 04:48 UTC
Hi team, 
can we expose the cloud zones details when a private link Dedicated SingleZone Cluster has been deployed 

Scenario: set up a single zone confluent cluster with Private link network type
Cloud provider: Azure

we have deployed a single zone private link type Cluster,  we need created a private endpoint, then end to end can work
but private endpoint setup depends on which zones that Cluster located.

i see in confluent cloud get cluster api, its response contains zones information, but can not get zones information in Terraform, 

the example as below
GET https://api.confluent.cloud/cmk/v2/clusters/lkc-prxvzm?environment=env-38onvm
```
{
    "api_version": "cmk/v2",
    "id": "lkc-prxvzm",
    "kind": "Cluster",
    "metadata": {
        "created_at": "2023-03-01T03:36:10.758161Z",
        "resource_name": "crn://confluent.cloud/organization=b0cc23f2-3d22-4acf-b3a1-eb809d6185b6/environment=env-38onvm/cloud-cluster=lkc-prxvzm/kafka=lkc-prxvzm",
        "self": "https://api.confluent.cloud/cmk/v2/clusters/lkc-prxvzm",
        "updated_at": "2023-03-01T04:07:47.18622Z"
    },
    "spec": {
        "api_endpoint": "https://lkaclkc-prxvzm-pd5zl6.eastus.azure.glb.confluent.cloud:443",
        "availability": "SINGLE_ZONE",
        "cloud": "AZURE",
        "config": {
            "cku": 1,
            "kind": "Dedicated",
            "zones": [
                "2"
            ]
        },
        "display_name": "hhhh",
        "environment": {
            "id": "env-38onvm",
            "related": "https://api.confluent.cloud/org/v2/environments/env-38onvm",
            "resource_name": "crn://confluent.cloud/organization=b0cc23f2-3d22-4acf-b3a1-eb809d6185b6/environment=env-38onvm"
        },
        "http_endpoint": "https://lkc-prxvzm-pd5zl6.eastus.azure.glb.confluent.cloud:443",
        "kafka_bootstrap_endpoint": "lkc-prxvzm-pd5zl6.eastus.azure.glb.confluent.cloud:9092",
        "network": {
            "id": "n-pd5zl6",
            "related": "https://api.confluent.cloud/networking/v1/networks/n-pd5zl6",
            "resource_name": "crn://confluent.cloud/network=n-pd5zl6"
        },
        "region": "eastus"
    },
    "status": {
        "cku": 1,
        "phase": "PROVISIONED"
    }
}
```

in our terraform automation deploy confluent cloud cluster stage, we need this zones information
so can we expose the  "zones": ["2"] information in the terraform like this https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_cluster#attributes-reference

Thanks,
Libo HuangFu

**Comment by linouk23** [comment] 2023-03-01 06:28
@huangfulibo thanks for creating the issue!

I've got 2 quick questions:

1. Did you leverage [dedicated-privatelink-azure-kafka-acls](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-azure-kafka-acls) example when setting up PL cluster on Azure? That example sets up DNS automatically.
2. Could you confirm that's a duplicate of https://github.com/confluentinc/terraform-provider-confluent/issues/132?

**Comment by linouk23** [comment] 2023-03-01 23:17
@huangfulibo see our latest [1.34.0](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.34.0) release where we

> Added support for new computed zones attribute of confluent_kafka_cluster [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_kafka_cluster) in a [Generally Available lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)

**Closed by linouk23** 2023-03-01 23:17 UTC
Labels: enhancement, work-in-progress

**Comment by huangfulibo** [comment] 2023-03-02 03:12
Hi @linouk23 
Ye,  it is  a duplicate of https://github.com/confluentinc/terraform-provider-confluent/issues/132


Thanks for quick response
