### ISSUE TITLE
Feature request: confluent user resource 

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/terraform-provider-confluent#281] opened 2023-07-10 06:38 UTC
Resource for confluent_invitation can be implemented for creating confluent users. Also, While sending invitations to a particular identity, role binding can be implemented as same as it's present when an invitation is sent via UI. This is not present in the confluent terraform provider. Here, once the user is created after sending the invitation, only then it can be assigned roles(different from the confluent UI).

**Comment by linouk23** [comment] 2023-07-10 17:35
👋 @VipulZopSmart!

Thanks for creating this issue! Closing as a duplicate of https://github.com/confluentinc/terraform-provider-confluent/issues/263

**Closed by linouk23** 2023-07-10 17:35 UTC
