### ISSUE TITLE
confluent_kafka_cluster http_endpoint not being populated when created with a dedicated block

### ISSUE THREAD

**Issue by morganrowse** [confluentinc/terraform-provider-confluent#46] opened 2022-05-25 08:39 UTC
Hi all,

Looking for some help here, 

I'm trying to create a cluster following the provided example [`dedicated-privatelink-aws-kafka-acls`](https://github.com/confluentinc/terraform-provider-confluent/tree/b64cebea5f2d1f6df70dec6c74e90d433feb12b7/examples/configurations/dedicated-privatelink-aws-kafka-acls) and keep running into issue with the dedicated cluster type.

It appears that the `confluent_kafka_cluster` resource does not expose the `http_endpoint` attribute when created with a `dedicated` block and I am unable to find the outputted attribute elsewhere. This seems to break the above example

Error in question at plan time
```
│ Error: invalid value for http_endpoint (the REST endpoint must start with 'https://')
│ 
│   with confluent_kafka_topic.orders,
│   on confluent.tf line 96, in resource "confluent_kafka_topic" "orders":
│   96:   http_endpoint = confluent_kafka_cluster.cluster.http_endpoint
```

Tried with version `0.8.1` and `0.8.0` of the provider

In my past experience with the provider using `standard` or `basic` config blocks. The `http_endpoint` attribute seems to be  correctly populated which allows topic and api key creation using the Terraform attribute

When outputting the `http_endpoint` attribute I can see that it is set to an empty string

```terraform
resource "confluent_kafka_cluster" "cluster" {
  display_name = "cluster"
  availability = "MULTI_ZONE"
  cloud        = "AWS"
  region       = local.remote_state_config.region

  dedicated {
    cku = 2
  }

  environment {
    id = confluent_environment.<env_name>.id
  }

  network {
    id = confluent_network.<net_name>.id
  }
}

output "endpoint" {
  value = confluent_kafka_cluster.cluster.http_endpoint
}
```

Terraform output
```
endpoint = ""
```

Just checking in that this attribute is being populated in your code when using dedicated clusters.

Thanks in advance

**Comment by linouk23** [comment] 2022-05-25 15:08
Thanks for reporting the issue @morganrowse!

That seems to be a duplicate of #14, please see [this comment](https://github.com/confluentinc/terraform-provider-confluent/issues/14#issuecomment-1120260571) for more details.

**Closed** 2022-05-25 15:13 UTC
Labels: bug
