### ISSUE TITLE
confluent_kafka_topic - Cannot import topic resource in a dedicated cluster

### ISSUE THREAD

**Issue by LiquoriChris** [confluentinc/terraform-provider-confluent#184] opened 2023-01-30 14:08 UTC
Hello,

I am having an issue importing topics when the cluster type is `dedicated`. The config block is an empty block in the state file after import.

```
terraform version: 1.3.6
Confluent Cloud Provider: 1.26.0
```

Example:
```
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.26.0"
    }
  }
}

provider "confluent" {
  cloud_api_key    = "<api_key>"
  cloud_api_secret = "<api_secret>"
}

resource "confluent_kafka_cluster" "cluster" {
  display_name = "<cluster>"
  region       = "eastus2"
  availability = "SINGLE_ZONE"
  cloud        = "AZURE"
  environment {
    id = "<env_id>"
  }
  dedicated {
    cku = 1
  }
}

resource "confluent_kafka_topic" "topic" {
  kafka_cluster {
    id = confluent_kafka_cluster.cluster.id
  }
  topic_name       = "topic"
  partitions_count = 6
  rest_endpoint    = confluent_kafka_cluster.cluster.rest_endpoint
  config = {
    "cleanup.policy"                        = "delete"
    "confluent.key.schema.validation"       = "false"
    "confluent.key.subject.name.strategy"   = "io.confluent.kafka.serializers.subject.TopicNameStrategy"
    "confluent.value.schema.validation"     = "false"
    "confluent.value.subject.name.strategy" = "io.confluent.kafka.serializers.subject.TopicNameStrategy"
    "delete.retention.ms"                   = "86400000"
    "max.compaction.lag.ms"                 = "9223372036854775807"
    "max.message.bytes"                     = "2097164"
    "message.timestamp.difference.max.ms"   = "9223372036854775807"
    "message.timestamp.type"                = "CreateTime"
    "min.compaction.lag.ms"                 = "0"
    "min.insync.replicas"                   = "2"
    "retention.bytes"                       = "-1"
    "retention.ms"                          = "604800000"
    "segment.bytes"                         = "104857600"
    "segment.ms"                            = "604800000"
  }
  credentials {
    key    = "<cluster_api_key"
    secret = "<cluster_api_secret>"
  }
  lifecycle {
    prevent_destroy = true
  }
}
```
State File after import:
```
{
  "version": 4,
  "terraform_version": "1.3.6",
  "serial": 6,
  "lineage": "082cc1c7-2166-44ae-945f-95ea099240ab",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "confluent_kafka_topic",
      "name": "topic",
      "provider": "provider[\"registry.terraform.io/confluentinc/confluent\"]",
      "instances": [
        {
          "schema_version": 2,
          "attributes": {
            "config": {},
            "credentials": [
              {
                "key": "<cluster_api_key>",
                "secret": "<cluster_api_secret>"
              }
            ],
            "id": "<cluster_id>/<topic_name>",
            "kafka_cluster": [
              {
                "id": "<cluster_id>"
              }
            ],
            "partitions_count": 6,
            "rest_endpoint": "<cluster_rest_endpoint>",
            "topic_name": "topic"
          },
          "sensitive_attributes": [],
          "private": "<redacted>"
        }
      ]
    }
  ],
  "check_results": null
}
```
Importing topics on `basic` cluster works and the config block with default properties are imported successfully.

Thanks for your help.

**Comment by LiquoriChris** [comment] 2023-02-14 19:17
Hello,

Just checking in to see if there is any update with this issue?

Thanks

**Comment by linouk23** [comment] 2023-02-17 07:30
@LiquoriChris thanks for creating an issue!

I've just tried to reproduce an issue: created a topic via UI, and then copied your config and run `terraform import ...`.

Then I can see:
```
$ terraform state show confluent_kafka_topic.topic               
# confluent_kafka_topic.topic:
resource "confluent_kafka_topic" "topic" {
    config           = {
        "cleanup.policy"                        = "delete"
        "confluent.key.schema.validation"       = "false"
        "confluent.key.subject.name.strategy"   = "io.confluent.kafka.serializers.subject.TopicNameStrategy"
        "confluent.value.schema.validation"     = "false"
        "confluent.value.subject.name.strategy" = "io.confluent.kafka.serializers.subject.TopicNameStrategy"
        "delete.retention.ms"                   = "86400000"
        "max.compaction.lag.ms"                 = "9223372036854775807"
        "max.message.bytes"                     = "2097164"
        "message.timestamp.difference.max.ms"   = "9223372036854775807"
        "message.timestamp.type"                = "CreateTime"
        "min.compaction.lag.ms"                 = "0"
        "min.insync.replicas"                   = "2"
        "retention.bytes"                       = "-1"
        "retention.ms"                          = "604800000"
        "segment.bytes"                         = "104857600"
        "segment.ms"                            = "604800000"
    }
    id               = "lkc-kxpnj2/topic_0"
    partitions_count = 6
    rest_endpoint    = "https://pkc-...:443"
    topic_name       = "topic_0"

    credentials {
        key    = (sensitive value)
        secret = (sensitive value)
    }

    kafka_cluster {
        id = "lkc-kxpnj2"
    }
}
$ terraform plan                                  
confluent_kafka_topic.topic: Refreshing state... [id=lkc-kxpnj2/topic_0]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

Also it seems like all of your settings are default values -- so if you created a topic via CLI / TF you should set your config to `config = {}` before importing it. If you created a topic via UI you should do the following:
![image](https://user-images.githubusercontent.com/5459870/219578731-5cf82b8f-6f80-4ab8-979a-f1f5b8c9a90e.png)


Let me know whether it helps!

**Comment by LiquoriChris** [comment] 2023-02-17 16:19
Which version of the provider did you use? With `1.26.0`, the TF was trying to re-create the topic resource because there were changes in the config.

Thanks.

**Comment by linouk23** [comment] 2023-02-17 16:20
@LiquoriChris could you share the output from TF plan after importing?

**Comment by linouk23** [comment] 2023-02-17 16:54
@LiquoriChris Thanks! Could you try again but use `config = {}` (or omit it) in your TF configuration?

**Comment by linouk23** [comment] 2023-02-17 16:56
The idea here `config` should only contain non-default values whereas it seems like all of your topic settings are set to their defaults (unless they were created via UI since UI uses old API still): 
![image](https://user-images.githubusercontent.com/5459870/219715655-c2b5a1f9-0889-4192-9bfa-2801610c348d.png)

**Comment by LiquoriChris** [comment] 2023-02-17 17:29
Right... It did work with `config = {}`, however, for `basic` clusters... It does work with default values in the `config` block. 

State file in `basic` cluster:

```
{
      "module": "module.confluent_cluster",
      "mode": "managed",
      "type": "confluent_kafka_topic",
      "name": "topic",
      "provider": "provider[\"registry.terraform.io/confluentinc/confluent\"]",
      "instances": [
        {
          "index_key": "<topic_name>",
          "schema_version": 2,
          "attributes": {
            "config": {
              "cleanup.policy": "delete",
              "delete.retention.ms": "86400000",
              "max.compaction.lag.ms": "9223372036854775807",
              "max.message.bytes": "2097164",
              "message.timestamp.difference.max.ms": "9223372036854775807",
              "message.timestamp.type": "CreateTime",
              "min.compaction.lag.ms": "0",
              "min.insync.replicas": "2",
              "retention.bytes": "-1",
              "retention.ms": "604800000",
              "segment.bytes": "104857600",
              "segment.ms": "604800000"
            },
            "credentials": [
              {
                "key": "<key>",
                "secret": "<secret>"
              }
            ],
            "id": "<cluster_id>/<topic_name>",
            "kafka_cluster": [
              {
                "id": "<cluster_id>"
              }
            ],
            "partitions_count": 1,
            "rest_endpoint": "<rest_endpoint>",
            "topic_name": "topic_name"
          },
          "sensitive_attributes": [],
          "private": "<redacted>"
        }
```

plan:
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

**Comment by LiquoriChris** [comment] 2023-02-17 17:40
Also, if I remove the `config` blocks from the state file in a basic cluster, this is what the plan looks like:

```
# module.confluent_cluster.confluent_kafka_topic.topic["<topic_name>"] will be updated in-place
  ~ resource "confluent_kafka_topic" "topic" {
      ~ config           = {
          - "cleanup.policy"                      = "delete" -> null
          - "delete.retention.ms"                 = "86400000" -> null
          - "max.compaction.lag.ms"               = "9223372036854775807" -> null
          - "max.message.bytes"                   = "2097164" -> null
          - "message.timestamp.difference.max.ms" = "9223372036854775807" -> null
          - "message.timestamp.type"              = "CreateTime" -> null
          - "min.compaction.lag.ms"               = "0" -> null
          - "min.insync.replicas"                 = "2" -> null
          - "retention.bytes"                     = "-1" -> null
          - "retention.ms"                        = "604800000" -> null
          - "segment.bytes"                       = "104857600" -> null
          - "segment.ms"                          = "604800000" -> null
        }
        id               = "<cluster_id>/<topic_name>"
        # (3 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

**Comment by linouk23** [comment] 2023-02-17 19:20
@LiquoriChris what if you add all these topic settings to Basic cluster TF config?
```
config           = {
          - "cleanup.policy"                      = "delete" -> null
          - "delete.retention.ms"                 = "86400000" -> null
          - "max.compaction.lag.ms"               = "9223372036854775807" -> null
          - "max.message.bytes"                   = "2097164" -> null
          - "message.timestamp.difference.max.ms" = "9223372036854775807" -> null
          - "message.timestamp.type"              = "CreateTime" -> null
          - "min.compaction.lag.ms"               = "0" -> null
          - "min.insync.replicas"                 = "2" -> null
          - "retention.bytes"                     = "-1" -> null
          - "retention.ms"                        = "604800000" -> null
          - "segment.bytes"                       = "104857600" -> null
          - "segment.ms"                          = "604800000" -> null
        }
```

**Comment by linouk23** [comment] 2023-02-17 19:26
btw I'd also recommend using [Option #2](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-2-manage-a-single-kafka-cluster-in-the-same-terraform-workspace) to avoid having credentials / kafka_cluster blocks in topic definition.

**Comment by LiquoriChris** [comment] 2023-02-17 19:34
Yes. In the process of updating that config. The above would work, but we update some of the settings set as the `cleanup.policy` `max.message.bytes` etc...

**Comment by linouk23** [comment] 2023-02-17 19:35
Sure, let's run `terraform plan` first and then try to update topic settings and see whether it works. Thank you @LiquoriChris!

**Comment by LiquoriChris** [comment] 2023-02-17 19:52
It does work in that config above. That is how I have it setup now for the topic resource.

topic:
```
resource "confluent_kafka_topic" "topic" {
  for_each = local.topic_map
  kafka_cluster {
    id = confluent_kafka_cluster.cluster.id
  }
  topic_name       = each.value.topic_name
  partitions_count = each.value.partitions_count
  rest_endpoint    = confluent_kafka_cluster.cluster.rest_endpoint
  config = {
    "cleanup.policy"                        = each.value.cleanup_policy
    "delete.retention.ms"                   = "86400000"
    "max.compaction.lag.ms"                 = "9223372036854775807"
    "max.message.bytes"                     = each.value.max_message_bytes
    "message.timestamp.difference.max.ms"   = "9223372036854775807"
    "message.timestamp.type"                = "CreateTime"
    "min.compaction.lag.ms"                 = "0"
    "min.insync.replicas"                   = "2"
    "retention.bytes"                       = "-1"
    "retention.ms"                          = each.value.retention_ms
    "segment.bytes"                         = "104857600"
    "segment.ms"                            = "604800000"
    "confluent.key.schema.validation"       = var.cluster_type == "dedicated" ? false : null
    "confluent.value.schema.validation"     = var.cluster_type == "dedicated" ? false : null
    "confluent.key.subject.name.strategy"   = var.cluster_type == "dedicated" ? "io.confluent.kafka.serializers.subject.TopicNameStrategy" : null
    "confluent.value.subject.name.strategy" = var.cluster_type == "dedicated" ? "io.confluent.kafka.serializers.subject.TopicNameStrategy" : null
  }
  credentials {
    key    = var.confluent_cloud_cluster_api_key
    secret = var.confluent_cloud_cluster_api_secret
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

variables:
```
variable "topic" {
  description = "Object type to create a new topic in a cluster."
  type = list(object({
    topic_name        = string
    partitions_count  = optional(string, "6")
    cleanup_policy    = optional(string, "delete")
    max_message_bytes = optional(string, "2097164")
    retention_ms      = optional(string, "604800000")
  }))
}
```

**Comment by linouk23** [comment] 2023-02-17 19:53
Great work @LiquoriChris! Are there any other questions left here?

**Comment by LiquoriChris** [comment] 2023-02-17 19:56
Yes, the issue still remains in a dedicated cluster... The topic settings do not get imported from the cluster... There is only an empty config block. The `basic` cluster is working as expected... I need to be able to import the config block in a dedicated cluster.

**Comment by linouk23** [comment] 2023-02-17 19:57
@LiquoriChris empty config means all topic settings are set to their default values which _they are_ in fact. You can add new topic settings to override default values and it'll work. Let me know if that helps.

**Comment by LiquoriChris** [comment] 2023-02-17 23:53
Understood. So I just confirmed that one of our clusters, the topics were created from the ui. That config is necessary for import but if the topics were created via cli, the config block isn't necessary unless I need to update a setting. Is that correct? Thanks for your help!

**Comment by linouk23** [comment] 2023-02-17 23:55
That's exactly right! I'm going to close this issue then but feel free to open a new one if you have any other questions 👍

**Closed by linouk23** 2023-02-17 23:55 UTC
Labels: question
