### ISSUE TITLE
Feature request: "Stream Governance Packages" terraform resource

### ISSUE THREAD

**Issue by johnnyplaydrums** [confluentinc/terraform-provider-confluent#114] opened 2022-09-28 16:26 UTC
Hello! I've recently started using the confluent terraform provider, and so far it's been a great experience. Thank you for creating this provider! After creating a cluster, I noticed that features like Schema Registry were turned off by default, and I needed to select a `Stream Governance Packages` in order to turn that feature on. I don't see the Stream Governance Packages in the terraform provider, which means I would need to enable it by hand. We are trying to fully automate the process for creating kafka clusters and am hoping we can do that mostly through the terraform provider, with some help from the confluent API where needed. Can you add the Stream Governance Packages as a resource in terraform? At first glance, I don't see API support for Stream Governance Packages, so that may be the blocker here. If that's the case, where should I file a feature request to add Stream Governance Packages management to the API? Thank you!

**Comment by linouk23** [comment] 2022-09-29 06:40
Thanks for creating this issue @johnnyplaydrums and thanks for the kind words!

You're absolutely right, first we'd need to get a public [API](https://docs.confluent.io/cloud/current/api.html) for it, I've just created an internal feature request for a relevant team 🤞. Will try to report back once I get the response.

**Comment by luggage66** [comment] 2022-10-04 14:32
I am updating from `Mongey/confluent` and the missing schema registry support is blocking us. The old provider is not longer compatible with the confluent API but the new one has no way to make api keys for schema registry. I tried using the values I imported from an existing resource, but they are not valid:

```
managed_resource {
    id          = "lsrc-XXXXX"
    api_version = "stream-governance/v2"
    kind        = "SchemaRegistry"

    environment {
      id = confluent_environment.environment.id
    }
  }
  ```
  
  Gives error: 
  
  ```
  expected managed_resource.0.kind to be one of [Cluster], got SchemaRegistry
  expected managed_resource.0.api_version to be one of [cmk/v2], got stream-governance/v2
  invalid value for managed_resource.0.id (the resource ID must be of the form 'lkc-')
  ```
  
  Also I see no way to retrieve the URL for the schema registry.

**Comment by linouk23** [comment] 2022-10-04 18:29
👋 @luggage66 that's very exciting to hear that you're trying to use TF Provider for Confluent!

We're aware of this issue (see #5) and it's on the roadmap.

**Comment by linouk23** [comment] 2022-10-05 21:56
Actually when I think about this issue again, I feel like enabling SG is the same thing as creating a SG cluster, in other words, this is a duplicate of #5 so I'll close this issue.

**Closed by linouk23** 2022-10-05 21:56 UTC
Labels: new-feature-request

**Comment by linouk23** [comment] 2022-10-27 03:46
update: we [released](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1100-october-26-2022) a new `1.10.0` version of TF Provider where we dded new `confluent_stream_governance_cluster` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_stream_governance_cluster) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_stream_governance_cluster) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

cc @johnnyplaydrums @luggage66

**Comment by johnnyplaydrums** [comment] 2022-11-01 17:29
Really awesome turnaround time on this feature! Thank you all so much!
