### ISSUE TITLE
Cloud Api keys if already exist,Plan creates new keys. 

### ISSUE THREAD

**Issue by Davinder2609** [confluentinc/terraform-provider-confluent#265] opened 2023-05-23 15:51 UTC
Can we implement Cloud Api keys if already exist,Plan does not create new keys.

**Comment by linouk23** [comment] 2023-05-24 23:18
> I created Kafka Api keys for app-consumer,when next time I run pipeline it should not created other api keys.
Is it any way I can restrict that.

Could you share your TF config? It's not clear why pipeline created other API Keys if you have created Kafka API Key already. @Davinder2609

**Comment by Davinder2609** [comment] 2023-05-25 19:20
@linouk23 
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.34.0"
    }
  }
}

provider "confluent" {
  cloud_api_key    = var.confluent_kafka_cloud_api_key
  cloud_api_secret = var.confluent_kafka_cloud_api_secret
}

resource "confluent_service_account" "ServiceAccount" {
  display_name = var.confluent_kafka_service_account_name
  description  = var.confluent_kafka_service_account_description
  lifecycle {
    prevent_destroy = true
  }
}

**Comment by linouk23** [comment] 2023-05-25 22:13
I see, does `terraform plan` for this pipeline results in creation of any API Keys at all?

BTW `cloud_api_key = var.confluent_kafka_cloud_api_key` make sure that `confluent_kafka_cloud_api_key` here is Cloud API Key and not Kafka API Key.

**Comment by linouk23** [comment] 2023-05-25 22:13
cc @Davinder2609

**Comment by Davinder2609** [comment] 2023-05-30 16:57
@linouk23  Yes this plan create Cluster Api key and SchemaRegistry keys.but issue is when we re run this plan again.It created Keys again

**Comment by linouk23** [comment] 2023-05-30 17:12
It sounds a little bit unexpected to me @Davinder2609 since your .tf config doesn't have any API Keys defined at all. Do you want to share your `terraform plan` output (make sure to delete all the sensitive information) that shows creation of Cluster / SR API Keys?

**Comment by Davinder2609** [comment] 2023-05-30 18:42
@linouk23 
  # Initialize terraform
  terraform init
  echo "Creating terraform plan....."
  # Creation of terraform plan
  terraform plan -var "confluent_kafka_service_account_id=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_ID" \
                -var "confluent_kafka_cloud_api_key=$CONFLUENT_KAFKA_CLOUD_API_KEY" \
                -var "confluent_kafka_cloud_api_secret=$CONFLUENT_KAFKA_CLOUD_API_secret" \
                -var "confluent_kafka_env_id=$CONFLUENT_KAFKA_ENV_ID" \
                -var "confluent_kafka_cluster_id=$CONFLUENT_KAFKA_CLUSTER_ID" \
                -var "confluent_schema_cluster_id=$CONFLUENT_SCHEMA_CLUSTER_ID" \
                -var "confluent_kafka_cluster_rest_end_point=$CONFLUENT_KAFKA_CLUSTER_REST_END_POINT" \
                -var "confluent_kafka_service_account_name=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_NAME" \
                var"confluent_kafka_service_account_description=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_DESCRIPTION" \
                -out output.terraform
  echo "Execution of terraform main plan module to create service account and schema registry keys is completed."
  terraform apply "output.terraform"

  #creating json files to add keys.
  echo "Creating terraform deployment output json file."
  terraform output -json > $TERRAFORM_MAIN_DIR/keys.json

If We re run this plan keys will created again

**Comment by linouk23** [comment] 2023-05-30 18:46
Gotcha, could you share the output of 
```
terraform plan -var "confluent_kafka_service_account_id=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_ID"
-var "confluent_kafka_cloud_api_key=$CONFLUENT_KAFKA_CLOUD_API_KEY"
-var "confluent_kafka_cloud_api_secret=$CONFLUENT_KAFKA_CLOUD_API_secret"
-var "confluent_kafka_env_id=$CONFLUENT_KAFKA_ENV_ID"
-var "confluent_kafka_cluster_id=$CONFLUENT_KAFKA_CLUSTER_ID"
-var "confluent_schema_cluster_id=$CONFLUENT_SCHEMA_CLUSTER_ID"
-var "confluent_kafka_cluster_rest_end_point=$CONFLUENT_KAFKA_CLUSTER_REST_END_POINT"
-var "confluent_kafka_service_account_name=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_NAME"
var"confluent_kafka_service_account_description=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_DESCRIPTION"
```
@Davinder2609 

Based on
```
terraform {
required_providers {
confluent = {
source = "confluentinc/confluent"
version = "1.34.0"
}
}
}

provider "confluent" {
cloud_api_key = var.confluent_kafka_cloud_api_key
cloud_api_secret = var.confluent_kafka_cloud_api_secret
}

resource "confluent_service_account" "ServiceAccount" {
display_name = var.confluent_kafka_service_account_name
description = var.confluent_kafka_service_account_description
lifecycle {
prevent_destroy = true
}
}
```

it looks like your TF should only create 1 service account.

**Comment by linouk23** [comment] 2023-05-30 19:17
Are you sure there's just one .tf file in your folder / module / $TERRAFORM_MAIN_DIR? @Davinder2609

**Comment by Davinder2609** [comment] 2023-05-30 19:32
@linouk23  we have main.tf, output.tf, variables.tf files

**Comment by linouk23** [comment] 2023-05-30 20:06
Sounds good @Davinder2609!

Gotcha, could you share the output of

```
terraform plan -var "confluent_kafka_service_account_id=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_ID"
-var "confluent_kafka_cloud_api_key=$CONFLUENT_KAFKA_CLOUD_API_KEY"
-var "confluent_kafka_cloud_api_secret=$CONFLUENT_KAFKA_CLOUD_API_secret"
-var "confluent_kafka_env_id=$CONFLUENT_KAFKA_ENV_ID"
-var "confluent_kafka_cluster_id=$CONFLUENT_KAFKA_CLUSTER_ID"
-var "confluent_schema_cluster_id=$CONFLUENT_SCHEMA_CLUSTER_ID"
-var "confluent_kafka_cluster_rest_end_point=$CONFLUENT_KAFKA_CLUSTER_REST_END_POINT"
-var "confluent_kafka_service_account_name=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_NAME"
var"confluent_kafka_service_account_description=$CONFLUENT_KAFKA_SERVICE_ACCOUNT_DESCRIPTION"
```

It's also kinda weird that you use that many variables given that you're not using them in
```

provider "confluent" {
cloud_api_key = var.confluent_kafka_cloud_api_key
cloud_api_secret = var.confluent_kafka_cloud_api_secret
}

resource "confluent_service_account" "ServiceAccount" {
display_name = var.confluent_kafka_service_account_name
description = var.confluent_kafka_service_account_description
lifecycle {
prevent_destroy = true
}
}
```

Based on the overall description, it appears to be a misconfiguration of Terraform rather than an issue with the TF Provider for Confluent. I am inclined to resolve this issue since I am unable to reproduce it. However, if you could provide a complete output of terraform plan that highlights the creation of all these new API Keys (`confluent_api_key`), it would be helpful.

**Comment by Davinder2609** [comment] 2023-05-31 17:04
@linouk23 
Changing to terraform main directory

[0m[1mInitializing the backend...[0m

[0m[1mInitializing provider plugins...[0m
- Finding confluentinc/confluent versions matching "1.22.0"...
- Installing confluentinc/confluent v1.22.0...
- Installed confluentinc/confluent v1.22.0 (signed by a HashiCorp partner, key ID [0m[1mD4[0m[0m)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m
[0m[1mconfluent_service_account.ServiceAccount: Importing from ID "sa-03r***"...[0m
[0m[1m[32mconfluent_service_account.ServiceAccount: Import prepared![0m
[0m[32m  Prepared confluent_service_account for import[0m
[0m[1mconfluent_service_account.ServiceAccount: Refreshing state... [id=sa-03r****][0m
[0m[32m
Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
[0m
Creating terraform plan.....
[0m[1mconfluent_service_account.ServiceAccount: Refreshing state... [id=sa-03r**][0m

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  [32m+[0m create
  [33m~[0m update in-place
[0m
Terraform will perform the following actions:

[1m  # confluent_api_key.kafka-cluster-api-key[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "confluent_api_key" "kafka-cluster-api-key" {
      [32m+[0m [0m[1m[0mdescription[0m[0m            = (sensitive value)
      [32m+[0m [0m[1m[0mdisable_wait_for_ready[0m[0m = false
      [32m+[0m [0m[1m[0mdisplay_name[0m[0m           = (sensitive value)
      [32m+[0m [0m[1m[0mid[0m[0m                     = (known after apply)
      [32m+[0m [0m[1m[0msecret[0m[0m                 = (sensitive value)

      [32m+[0m [0mmanaged_resource {
          [32m+[0m [0m[1m[0mapi_version[0m[0m = "cmk/v2"
          [32m+[0m [0m[1m[0mid[0m[0m          = (sensitive value)
          [32m+[0m [0m[1m[0mkind[0m[0m        = "Cluster"

          [32m+[0m [0menvironment {
              [32m+[0m [0m[1m[0mid[0m[0m = (sensitive value)
            }
        }

      [32m+[0m [0mowner {
          [32m+[0m [0m[1m[0mapi_version[0m[0m = "iam/v2"
          [32m+[0m [0m[1m[0mid[0m[0m          = "sa-03r****"
          [32m+[0m [0m[1m[0mkind[0m[0m        = "User"
        }
    }

[1m  # confluent_api_key.schema-registry-api-key[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "confluent_api_key" "schema-registry-api-key" {
      [32m+[0m [0m[1m[0mdescription[0m[0m            = (sensitive value)
      [32m+[0m [0m[1m[0mdisable_wait_for_ready[0m[0m = false
      [32m+[0m [0m[1m[0mdisplay_name[0m[0m           = (sensitive value)
      [32m+[0m [0m[1m[0mid[0m[0m                     = (known after apply)
      [32m+[0m [0m[1m[0msecret[0m[0m                 = (sensitive value)

      [32m+[0m [0mmanaged_resource {
          [32m+[0m [0m[1m[0mapi_version[0m[0m = "srcm/v2"
          [32m+[0m [0m[1m[0mid[0m[0m          = (sensitive value)
          [32m+[0m [0m[1m[0mkind[0m[0m        = "Cluster"

          [32m+[0m [0menvironment {
              [32m+[0m [0m[1m[0mid[0m[0m = (sensitive value)
            }
        }

      [32m+[0m [0mowner {
          [32m+[0m [0m[1m[0mapi_version[0m[0m = "iam/v2"
          [32m+[0m [0m[1m[0mid[0m[0m          = "sa-03r***"
          [32m+[0m [0m[1m[0mkind[0m[0m        = "User"
        }
    }

[1m  # confluent_role_binding.schema-manager-schema-registry-admin[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "confluent_role_binding" "schema-manager-schema-registry-admin" {
      [32m+[0m [0m[1m[0mcrn_pattern[0m[0m = (sensitive value)
      [32m+[0m [0m[1m[0mid[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0mprincipal[0m[0m   = "User:sa-03r***"
      [32m+[0m [0m[1m[0mrole_name[0m[0m   = "DeveloperRead"
    }

[1m  # confluent_service_account.ServiceAccount[0m will be updated in-place[0m[0m
[0m  [33m~[0m[0m resource "confluent_service_account" "ServiceAccount" {
      # [33mWarning:[0m this attribute value will be marked as sensitive and will not
[0m      # display in UI output after applying this change. The value is unchanged.
      [33m~[0m [0m[1m[0mdescription[0m[0m  = (sensitive value)
      # [33mWarning:[0m this attribute value will be marked as sensitive and will not
[0m      # display in UI output after applying this change. The value is unchanged.
      [33m~[0m [0m[1m[0mdisplay_name[0m[0m = (sensitive value)
        [1m[0mid[0m[0m           = "sa-03r****"
        [90m# (2 unchanged attributes hidden)[0m[0m
    }

[0m[1mPlan:[0m 3 to add, 1 to change, 0 to destroy.
[0m[0m
[1mChanges to Outputs:[0m[0m
  [32m+[0m [0m[1m[0mkafka_cluster_api_key[0m[0m      = (sensitive value)
  [32m+[0m [0m[1m[0mkafka_cluster_api_secret[0m[0m   = (sensitive value)
  [32m+[0m [0m[1m[0mschema_registry_api_key[0m[0m    = (sensitive value)
  [32m+[0m [0m[1m[0mschema_registry_api_secret[0m[0m = (sensitive value)



Saved the plan to: output.terraform

To perform exactly these actions, run the following command to apply:
    terraform apply "output.terraform"
Execution of terraform main plan module to create service account and schema registry keys is completed.
Deploying terraform main plan module to create service account and schema registry keys.
[0m[1mconfluent_service_account.ServiceAccount: Modifying... [id=sa-03r****][0m[0m
[0m[1mconfluent_service_account.ServiceAccount: Modifications complete after 0s [id=sa-03r***][0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Creating...[0m[0m
[0m[1mconfluent_api_key.schema-registry-api-key: Creating...[0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Creating...[0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [10s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [10s elapsed][0m[0m
[0m[1mconfluent_api_key.schema-registry-api-key: Still creating... [10s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [20s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [20s elapsed][0m[0m
[0m[1mconfluent_api_key.schema-registry-api-key: Still creating... [20s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [30s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [30s elapsed][0m[0m
[0m[1mconfluent_api_key.schema-registry-api-key: Still creating... [30s elapsed][0m[0m
[0m[1mconfluent_api_key.schema-registry-api-key: Creation complete after 31s [id=JY***************][0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [40s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [40s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [50s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [50s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [1m0s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m0s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [1m10s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m10s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [1m20s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m20s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m30s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [1m30s elapsed][0m[0m
[0m[1mconfluent_role_binding.schema-manager-schema-registry-admin: Creation complete after 1m30s [id=rb-9BwJ7][0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m40s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m50s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [2m0s elapsed][0m[0m
[0m[1mconfluent_api_key.kafka-cluster-api-key: Creation complete after 2m2s [id=EE******************][0m
[0m[1m[32m
Apply complete! Resources: 3 added, 1 changed, 0 destroyed.
[0m[0m[1m[32m
Outputs:

[0mkafka_cluster_api_key = <sensitive>
kafka_cluster_api_secret = <sensitive>
schema_registry_api_key = <sensitive>
schema_registry_api_secret = <sensitive>
service_account_id = <sensitive>
Creating terraform deployment output json file.
Output json file is created.

**Comment by linouk23** [comment] 2023-06-01 16:02
OK so we can see that your TF config contains other resources listed outside of `main.tf`:
```
�[0m�[1mconfluent_role_binding.schema-manager-schema-registry-admin: Still creating... [1m10s elapsed]�[0m�[0m
�[0m�[1mconfluent_api_key.kafka-cluster-api-key: Still creating... [1m10s elapsed]�[0m�[0m

```

**Comment by linouk23** [comment] 2023-06-01 16:03
Moreover, it seems like you `terraform apply` went through:
```
Apply complete! Resources: 3 added, 1 changed, 0 destroyed.
```

**Comment by linouk23** [comment] 2023-06-02 13:23
Gotcha, well the question is why 

> Resource confluent_api_key.app-consumer-schema-registry-api-key has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. 

Could you remove `lifecycle.prevent_destroy` and rerun `terraform plan` to see a more detailed error message? @Davinder2609

**Comment by Davinder2609** [comment] 2023-06-06 13:58
without lifecycle.prevent_destroy -

Terraform will perform the following actions:

  # confluent_api_key.app-consumer-schema-registry-api-key must be replaced
-/+ resource "confluent_api_key" "app-consumer-schema-registry-api-key" {
      ~ id                     = "L******" -> (known after apply)
      ~ secret                 = (sensitive value)
        # (3 unchanged attributes hidden)

      ~ owner {
            id          = "sa-***"
          ~ kind        = "ServiceAccount" -> "User" # forces replacement
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

───────────────────────────────────

**Comment by Davinder2609** [comment] 2023-06-06 14:26
@linouk23 
lifecycle {

  prevent_destroy = true
}
is not working for schemaRegistry keys

**Comment by linouk23** [comment] 2023-06-06 14:38
Right and could you share IDs as I suggested in the message above? I wanted to double check it's not a backend bug even though I can't reproduce it locally now.

**Comment by linouk23** [comment] 2023-06-06 14:39
cc @Davinder2609

**Comment by linouk23** [comment] 2023-06-07 14:28
@Davinder2609 could you confirm that drift
```
  ~ owner {
        id          = "sa-***"
      ~ kind        = "ServiceAccount" -> "User" # forces replacement
        # (1 unchanged attribute hidden)
    }

    # (1 unchanged block hidden)
}
Plan: 1 to add, 0 to change, 1 to destroy.
```
went away and new output for `terraform plan` command is 
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
or something now so we could close this issue?

**Comment by Davinder2609** [comment] 2023-06-07 15:15
@linouk23  thanks ! You can close the issue.

**Closed** 2023-06-07 15:24 UTC
Labels: question

**Comment by Davinder2609** [comment] 2023-06-07 15:58
@linouk23  Is it any way we can restrict  cloud api key.schema key creation if already exist through terraform

**Comment by linouk23** [comment] 2023-06-07 18:15
I don't think so -- a user could use CLI / CC UI to create a new Schema Registry API Key if that's what your question is about. Feel free to create a new issue if anything.
