### ISSUE TITLE
Apply schema validation during terraform plan phase

### ISSUE THREAD

**Issue by xc-cre** [confluentinc/terraform-provider-confluent#218] opened 2023-03-09 15:17 UTC
When an incompatible change for a subject is pushed it currently only fails during apply run not during plan.
Background: We currently use confluent maven plugin for managing our schemas and run check-compatibility in our CI pipeline to prevent merging incompatible changes.
It would be great if compatibility could be checked during plan so issues could be detected upfront.

**Comment by nicholas-ebert** [comment] 2023-05-02 23:06
+ 1 for this, it would really help us. It's risky to rely on the compatibility check that runs during the apply step so we'd love to have this fail during plan.

**Comment by S1M0NM** [comment] 2023-05-04 06:32
@linouk23 whats the current status of this?

Today we had another error in the Apply step, but with a completely wrong error message.

```
Error: error creating Schema: error validating a schema: Compatibility check on the schema has failed against one or more versions in the subject, depending on how the compatibility is set.
See https://docs.confluent.io/platform/current/schema-registry/avro.html#sr-compatibility-types for details.
For example, if compatibility on the subject is set to BACKWARD, FORWARD, or FULL, the compatibility check is against the latest version.
If compatibility is set to one of the TRANSITIVE types, the check is against all previous versions.
 
 with module.<module-name>.confluent_schema.schema["<subject-name>"],
 on .terraform/modules/aiops/schema.tf line 1, in resource "confluent_schema" "schema":
1: resource "confluent_schema" "schema" {

```

Surprisingly, we didn't have a subject with that name yet, so there couldn't have been any previous versions that weren't compatible.
Using Confluent Cloud UI gave the following result:
`invalid name: "<namespace>.turnaround-results"`

The provider's error message is completely misleading, since at this point it is not a compatibility problem, but an invalid scheme.
The error message made me check a lot of other things instead of being able to fix the error directly.
If these checks were performed in the plan step, then I could have seen it via the build validation in the pull request before the merge.

**Comment by linouk23** [comment] 2023-05-04 18:42
Thanks everyone for creating the issue and providing all this feedback!

@S1M0NM could your share a minimal working example so I'd be able to reproduce this issue?

We did release a similar fix for `confluent_kafka_cluster` recently (https://github.com/confluentinc/terraform-provider-confluent/issues/221) so we should be in a great position to research a similar fix for `confluent_schema` resource 👍

**Comment by S1M0NM** [comment] 2023-05-06 07:44
@linouk23 sure, i just took an example from the Apache Avro Website and modified the name field.

```

{"namespace": "example.avro",
 "type": "record",
 "name": "Invalid-Record-Name",
 "fields": [
     {"name": "name", "type": "string"},
     {"name": "favorite_number",  "type": ["int", "null"]},
     {"name": "favorite_color", "type": ["string", "null"]}
 ]
}

```

the "name" can not contain minus what caused the error with a misleading error message.

**Comment by linouk23** [comment] 2023-06-01 04:37
@xc-cre @nicholas-ebert @S1M0NM @agoel2 @noahseger we've just released a new version of TF Provider for Confluent ([1.43.0](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.43.0)) that includes a fix for this issue.

Let us know if you're able to reproduce it when using [the latest version](https://github.com/confluentinc/terraform-provider-confluent/releases/tag/v1.43.0) of TF Provider!

**Closed by linouk23** 2023-06-01 04:37 UTC
Labels: question

**Comment by nicholas-ebert** [comment] 2023-06-01 16:47
Hey @linouk23, is this available in the Pulumi provider as well?
