### ISSUE TITLE
correlationId validation schema error when upgrading from 1.68.0 to 1.76.0

### ISSUE THREAD

**Issue by Andrei-Predoiu** [confluentinc/terraform-provider-confluent#388] opened 2024-05-22 06:44 UTC
We haven't changed anything in the code, it's a dependabot provider update where we see this on all of our `confluent_schema` objects.

```
│   with module.material-tech.module.abc.confluent_schema.main["test"],
│   on modules/topic/main.tf line 144, in resource "confluent_schema" "main":
│  144: resource "confluent_schema" "main" {
│ 
╵
╷
│ Error: error validating Schema: error validating a schema: [{errorType:'READER_FIELD_MISSING_DEFAULT_VALUE', description:'The field 'correlationId' at path '/fields/0' in the new schema has no default value and is missing in the old schema', additionalInfo:'correlationId'} {oldSchemaVersion: 2} {oldSchema: '{"type":"record","name":"CommonFctV1Avsc","namespace":"com.bestseller.schema.materialtech.common.v1","fields":[{"name":"result","type":{"type":"string","avro.java.string":"String"}},{"name":"details","type":{"type":"array","items":{"type":"record","name":"CommonFctV1DetailAvsc","fields":[{"name":"errorCode","type":{"type":"string","avro.java.string":"String"}},{"name":"message","type":{"type":"string","avro.java.string":"String"}},{"name":"payload","type":{"type":"record","name":"CommonFctV1PayloadAvsc","fields":[{"name":"key","type":{"type":"string","avro.java.string":"String"}},{"name":"value","type":{"type":"string","avro.java.string":"String"}}]}}]}}}]}'} {validateFields: 'true', compatibility: 'BACKWARD'}]
```

**Comment by petrkarytka** [comment] 2024-05-28 10:34
@Andrei-Predoiu seems the issue has already been reported #378

**Comment by linouk23** [comment] 2024-06-14 18:17
I'm closing this one as it's a duplicate of #378.

**Closed by linouk23** 2024-06-14 18:17 UTC
