### ISSUE TITLE
Change the Cluster Type parameter to one programmable

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#59] opened 2022-06-28 13:07 UTC
Scenario:
We do need to create clusters of different types like BASIC, STANDARD or DEDICATED...
Now, we do need to create one resource per Kafka Cluster Type like...

```
#Cluster BASIC
resource "confluent_kafka_cluster_v2" "cluster" {
  display_name = var.environment_name
  availability = var.availability
  cloud        = var.cloud
  region       = var.region
  basic {}

  environment {
    id = confluent_environment_v2.environment.id
  }
}
#Cluster DEDICATED
resource "confluent_kafka_cluster_v2" "cluster" {
  display_name = var.environment_name
  availability = var.availability
  cloud        = var.cloud
  region       = var.region
  dedicated {
    cku = 2
  }

  environment {
    id = confluent_environment_v2.environment.id
  }
}
````
Now we do need to create 3 different resources to do so because DEDICATED, STANDARD, and BASIC are arguments and as far as I know I cannot use those as variables.

The idea is to have instead an argument with properties, so then we can use the same resource for any kind of cluster:
```
**variables.tf**
variable cluster_type {
     description = "Type of the Cluster, can be BASIC, DEDICATED or STANDARD"
     default        = basic
}

**main.tf**
resource "confluent_kafka_cluster_v2" "cluster" {
  display_name = var.environment_name
  availability = var.availability
  cloud         = var.cloud
  region       = var.region
  type          = var.cluster_type

  environment {
    id = confluent_environment_v2.environment.id
  }
}
```

Maybe it would work as an object type as well:
```
variable cluster_settings {
  type = object({
        type                   = basic
      })
}
```

**Comment by PlugaruT** [comment] 2022-06-28 13:44
Maybe you can use the [dynamic blocks](https://www.terraform.io/language/expressions/dynamic-blocks) in TF for resource definition. We only have to deal with standard/basic and this is what we have:
```
resource "confluent_kafka_cluster" "default" {
  display_name = var.cluster_name
  availability = var.availability
  cloud        = "GCP"
  region       = var.region

  dynamic "standard" {
    for_each = var.basic_cluster ? [] : [1]
    content {}
  }

  dynamic "basic" {
    for_each = var.basic_cluster ? [1] : []
    content {}
  }

  environment {
    id = var.environment_id
  }
}

```

**Comment by rogerioefonseca** [comment] 2022-06-28 14:30
> aybe you can use the [dynamic blocks](https://www.terraform.io/language/expressions/dynamic-blocks) in TF for resource definition. We only have to deal with standard/basic and this is what we have:

Sounds a good option and super feasible.
Thanks for the tip.

**Comment by linouk23** [comment] 2022-06-28 18:20
Thanks for asking @rogerioefonseca and thanks for helping to answer this question @PlugaruT!

@rogerioefonseca that might be a duplicate of https://github.com/confluentinc/terraform-provider-confluentcloud/issues/52#issuecomment-1075508718, please see that comment for more context & why we designed it this way.

**Closed by linouk23** 2022-06-28 18:20 UTC
